<a href="https://colab.research.google.com/github/satyajitghana/TSAI-DeepNLP-END2.0/blob/main/06_Encoder_Decoder/Tweets_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [93]:
! pip install gdown==3.13.0 --quiet
! pip install spacy==3.0.6 --quiet
! pip install tweet-preprocessor --quiet
! pip install pytorch-lightning --quiet

     |████████████████████████████████| 808kB 5.2MB/s 
     |████████████████████████████████| 122kB 36.7MB/s 
     |████████████████████████████████| 10.6MB 32.6MB/s 
     |████████████████████████████████| 645kB 31.9MB/s 
     |████████████████████████████████| 829kB 38.5MB/s 
     |████████████████████████████████| 276kB 34.1MB/s 
     |████████████████████████████████| 1.3MB 30.5MB/s 
     |████████████████████████████████| 143kB 39.0MB/s 
     |████████████████████████████████| 296kB 29.6MB/s 
ERROR: tensorflow 2.5.0 has requirement tensorboard~=2.5, but you'll have tensorboard 2.4.1 which is incompatible.


In [ ]:
! python -m spacy download en_core_web_sm

In [2]:
! gdown https://drive.google.com/uc?id=1MMAXbWehsbs-tRpK2wxpF0UWrwC00hC5

Downloading...
From: https://drive.google.com/uc?id=1MMAXbWehsbs-tRpK2wxpF0UWrwC00hC5
To: /content/tweets.csv
100% 160k/160k [00:00<00:00, 5.07MB/s]


In [141]:
import pandas as pd
import preprocessor as p

from tqdm.auto import tqdm

tqdm.pandas()

/usr/local/lib/python3.7/dist-packages/tqdm/std.py:658: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  from pandas import Panel


In [142]:
dataset = pd.read_csv('tweets.csv')

In [143]:
dataset

tweets  labels
0     Obama has called the GOP budget social Darwini...       1
1     In his teen years, Obama has been known to use...       0
2     IPA Congratulates President Barack Obama for L...       0
3     RT @Professor_Why: #WhatsRomneyHiding - his co...       0
4     RT @wardollarshome: Obama has approved more ta...       1
...                                                 ...     ...
1359  @liberalminds Its trending idiot.. Did you loo...       0
1360  RT @AstoldByBass: #KimKardashiansNextBoyfriend...       0
1361  RT @GatorNation41: gas was $1.92 when Obama to...       1
1362  @xShwag haha i know im just so smart, i mean y...       1
1363  #OBAMA:  DICTATOR IN TRAINING.  If he passes t...       0

[1364 rows x 2 columns]

In [144]:
dataset['labels'].value_counts()

0    931
1    352
2     81
Name: labels, dtype: int64

In [150]:
def clean_tweet(tweet):
    tweet = tweet.replace("RT", "")
    tweet = p.clean(tweet).strip()
    tweet = tweet.replace(":", "")
    return tweet

In [151]:
dataset['tweets_cleaned'] = dataset['tweets'].progress_apply(clean_tweet)
dataset = dataset[dataset['tweets_cleaned'].str.len() > 2]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [152]:
dataset

tweets  ...                                     tweets_cleaned
0     Obama has called the GOP budget social Darwini...  ...  Obama has called the GOP budget social Darwini...
1     In his teen years, Obama has been known to use...  ...  In his teen years, Obama has been known to use...
2     IPA Congratulates President Barack Obama for L...  ...  IPA Congratulates President Barack Obama for L...
3     RT @Professor_Why: #WhatsRomneyHiding - his co...  ...   - his connection to supporters of Critical Ra...
4     RT @wardollarshome: Obama has approved more ta...  ...   Obama has approved more targeted assassinatio...
...                                                 ...  ...                                                ...
1359  @liberalminds Its trending idiot.. Did you loo...  ...  Its trending idiot.. Did you look at the tweet...
1360  RT @AstoldByBass: #KimKardashiansNextBoyfriend...  ...                                       Barack Obama
1361  RT @GatorNation41: gas was $1.92 when Obama to...  ...   gas was $1.92 when Obama took office...I gues...
1362  @xShwag haha i know im just so smart, i mean y...  ...  haha i know im just so smart, i mean you gotta...
1363  #OBAMA:  DICTATOR IN TRAINING.  If he passes t...  ...   DICTATOR IN TRAINING. If he passes this train...

[1351 rows x 3 columns]

In [153]:
idx = 700
dataset['tweets'].iloc[idx], dataset['tweets_cleaned'].iloc[idx]

('Small Biz News Obama to sign bill to help companies go public http://t.co/w8RSgU6t',
 'Small Biz News Obama to sign bill to help companies go public')

In [154]:
dataset.to_csv('tweets_cleaned.csv')

In [155]:
import torch
import torchtext
import gdown

import pytorch_lightning as pl

from torch.utils.data import Dataset, DataLoader, random_split

from torchtext.data.utils import get_tokenizer
from torchtext.vocab import build_vocab_from_iterator

import torchtext.experimental.functional as text_f

from pathlib import Path
from functools import partial

import pandas as pd
import preprocessor as p

from typing import *

In [167]:
class TweetsDataset(Dataset):
    """
    """

    URL = 'https://drive.google.com/uc?id=1gCEb9iRVYet15O4Tqvrj9Fjq9lVbSEQg'
    OUTPUT = 'tweets_cleaned.csv'
 

    def __init__(self, root, vocab=None, vectors=None, text_transforms=None, label_transforms=None, ngrams=1):
        """Initiate text-classification dataset.
        Args:
            vocab: Vocabulary object used for dataset.
        """

        super(self.__class__, self).__init__()

        # if split not in ['train', 'test']:
        #     raise ValueError(f'split must be either ["train", "test"] unknown split {split}')

        if vocab and vectors:
            raise ValueError(f'both vocab and vectors cannot be provided')

        self.vocab = vocab
        self.vectors = vectors

        gdown.cached_download(self.URL, Path(root) / self.OUTPUT)

        self.generate_tweet_dataset(Path(root) / self.OUTPUT)

        tokenizer = get_tokenizer("spacy", language="en_core_web_sm")

        # the text transform can only work at the sentence level
        # the rest of tokenization and vocab is done by this class
        self.text_transform = text_f.sequential_transforms(tokenizer, text_f.ngrams_func(ngrams))

        self.vocab_transforms = text_f.sequential_transforms()
        self.vector_transforms = text_f.sequential_transforms()

        def build_vocab(data, transforms):
            def apply_transforms(data):
                for line in data:
                    yield transforms(line)
            return build_vocab_from_iterator(apply_transforms(data), len(data))

        if self.vectors:
            self.vector_transforms = text_f.sequential_transforms(
                partial(vectors.get_vecs_by_tokens, lower_case_backup=True)
            )
        elif self.vocab is None:
            # vocab is always built on the train dataset
            self.vocab = build_vocab(self.dataset["tweets_cleaned"], self.text_transform)
    
        if self.vocab:
            self.vocab_transforms = text_f.sequential_transforms(
                text_f.vocab_func(self.vocab), text_f.totensor(dtype=torch.long)
            )

        if text_transforms is not None:
            self.text_transform = text_f.sequential_transforms(
                self.text_transform, text_transforms, self.vocab_transforms, self.vector_transforms 
            )
        else:
            self.text_transform = text_f.sequential_transforms(
                self.text_transform, self.vocab_transforms, self.vector_transforms
            )

        self.label_transform = text_f.sequential_transforms(text_f.totensor(dtype=torch.long))

    def generate_tweet_dataset(self, dataset_file):
        self.dataset = pd.read_csv(dataset_file)

    def __getitem__(self, idx):
        text = self.text_transform(self.dataset['tweets_cleaned'].iloc[idx])
        label = self.label_transform(self.dataset['labels'].iloc[idx])
        return label, text, self.dataset['tweets'].iloc[idx]

    def __len__(self):
        return len(self.dataset)

    @staticmethod
    def get_labels():
        return ['Negative', 'Positive', 'Neutral']

    def get_vocab(self):
        return self.vocab

    def get_vectors(self):
        return self.vectors

    def collator_fn(self, raw_texts=False):
        def collate_fn(batch):
            
            labels, sequences, raw_texts = zip(*batch)

            labels = torch.stack(labels)

            lengths = torch.LongTensor([len(sequence) for sequence in sequences])

            # print('before padding: ', sequences[40])

            if not self.vectors:
                pad_idx = self.get_vocab()['<pad>']
                sequences = torch.nn.utils.rnn.pad_sequence(sequences, 
                                                            padding_value = pad_idx,
                                                            batch_first=True
                                                            )
            # print('after padding: ', sequences[40])
            if raw_texts:
                return labels, sequences, lengths, raw_texts
            else:
                return labels, sequences, lengths
        
        return collate_fn

In [157]:
vectors = torchtext.vocab.GloVe("6B")

In [159]:
dataset = TweetsDataset(root='.', vectors=vectors)

File exists: tweets_cleaned.csv


In [160]:
dataset[0]

(tensor(1),
 tensor([[ 0.1030,  0.4800, -0.5092,  ..., -0.0370, -1.3354,  0.9289],
         [-0.2106,  0.2268,  0.0637,  ..., -0.6105, -0.2069, -0.1013],
         [ 0.0712,  0.3448,  0.0420,  ..., -0.0353, -0.5097,  0.1368],
         ...,
         [-0.6792, -0.1221, -0.2291,  ...,  0.0274, -0.2866, -0.0303],
         [-0.1018, -1.1882, -0.4792,  ...,  0.1053,  0.9321, -0.1999],
         [-0.1256,  0.0136,  0.1031,  ..., -0.3422, -0.0224,  0.1368]]),
 'Obama has called the GOP budget social Darwinism. Nice try, but they believe in social creationism.')

In [161]:
dataset[3]

(tensor(0),
 tensor([[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
         [ 0.0406, -0.0284,  0.2501,  ..., -0.7256, -0.1930,  0.2275],
         [-0.2213,  0.4714, -0.1666,  ..., -0.4044, -0.6878,  0.0392],
         ...,
         [ 0.0084,  0.2877, -0.2347,  ..., -0.6641,  0.1030,  0.1219],
         [ 0.4704,  0.1487,  0.1824,  ...,  0.3937, -0.5171,  0.9472],
         [ 0.2336, -0.3992, -0.2368,  ..., -0.4330,  0.0723,  0.4403]]),
 'RT @Professor_Why: #WhatsRomneyHiding - his connection to supporters of Critical Race Theory.... Oh wait, that was Obama, not Romney...')

In [87]:
train_size = int(0.8 * len(dataset))
test_size = len(dataset) - train_size
train_dataset, test_dataset = torch.utils.data.random_split(dataset, [train_size, test_size])

In [90]:
train_size

1091

In [88]:
train_dataset[0]

(tensor(0),
 tensor([[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
         [ 0.6947,  0.2218,  0.1053,  ...,  0.3487, -0.6308,  0.3809],
         [-0.6233, -0.4243, -0.0353,  ..., -0.1361,  0.0987,  0.6090],
         ...,
         [ 0.3165, -0.0019, -0.3633,  ..., -0.3862,  0.0104,  0.6200],
         [ 0.2336, -0.3992, -0.2368,  ..., -0.4330,  0.0723,  0.4403],
         [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]]),
 'RT @/SheCallsMeLarryThe "new" anti-Obama slur from the #RWNJ echo chamber is THUG? So we\'ve decided to just let ... http://t.co/lFYgXSNS')

In [89]:
test_dataset[0]

(tensor(0),
 tensor([[ 0.1191,  0.0495, -0.0815,  ...,  0.6728, -0.0497,  0.3084],
         [-0.0055,  0.0979,  0.3243,  ..., -0.2580, -0.5349, -0.3267],
         [ 0.1030,  0.4800, -0.5092,  ..., -0.0370, -1.3354,  0.9289],
         ...,
         [-0.0018, -0.3367, -0.1308,  ..., -0.9911, -0.4665,  0.1936],
         [ 0.2336, -0.3992, -0.2368,  ..., -0.4330,  0.0723,  0.4403],
         [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]]),
 "Examiner Editorial: Obama's budget, not Ryan's, is 'antithetical' to history: Speaking at the American Society o... http://t.co/mNhPMR5U")

In [168]:
class TweetsDataModule(pl.LightningDataModule):
    """
    DataModule for Tweets, train, val, test splits and transforms
    """

    name = "tweets"

    def __init__(
        self,
        data_dir: str = '.',
        val_split: int = 1000,
        num_workers: int = 2,
        batch_size: int = 128,
        *args,
        **kwargs,
    ):
        """
        Args:
            data_dir: where to save/load the data
            val_split: how many of the training images to use for the validation split
            num_workers: how many workers to use for loading data
            normalize: If true applies image normalize
            batch_size: desired batch size.
        """
        super().__init__(*args, **kwargs)

        self.data_dir = data_dir
        self.val_split = val_split
        self.num_workers = num_workers
        self.batch_size = batch_size

        self.dataset_train = ...
        self.dataset_val = ...
        self.dataset_test = ...
        self.vectors = ...

        self.Dataset = TweetsDataset

    def prepare_data(self):
        """Saves IMDB files to `data_dir`"""
        self.Dataset(self.data_dir)

    def setup(self, stage: Optional[str] = None):
        """Split the train and valid dataset"""
        
        self.vectors = torchtext.vocab.GloVe("6B")

        self._dataset = self.Dataset(self.data_dir, vectors=self.vectors)

        train_size = len(self._dataset) - self.val_split
        test_size = self.val_split
        train_dataset, test_dataset = torch.utils.data.random_split(self._dataset, [train_size, test_size])
        
        self.dataset_train = train_dataset
        self.dataset_test = test_dataset

    def train_dataloader(self):
        loader = DataLoader(
            self.dataset_train,
            batch_size=self.batch_size,
            shuffle=True,
            num_workers=self.num_workers,
            pin_memory=True,
            collate_fn=self.collator_fn
        )
        return loader

    def val_dataloader(self):
        loader = DataLoader(
            self.dataset_test,
            batch_size=self.batch_size,
            shuffle=False,
            num_workers=self.num_workers,
            pin_memory=True,
            collate_fn=self.collator_fn
        )
        return loader

    def test_dataloader(self):
        loader = DataLoader(
            self.dataset_test,
            batch_size=self.batch_size,
            shuffle=False,
            num_workers=self.num_workers,
            pin_memory=True,
            collate_fn=self.collator_fn
        )
        return loader

    def get_vocab(self):
        return self._dataset.get_vocab()
    
    def get_vectors(self):
        return self._dataset.get_vectors()

    def get_labels(self):
        return self._dataset.get_labels()
        
    @property
    def default_transforms(self):
        train_transforms = {
            'text_transforms': text_f.sequential_transforms(
                random_deletion,
                random_swap
            ),
            'label_transforms': None
        }
        test_transforms = {
            'text_transforms': None,
            'label_transforms': None
        }

        return train_transforms, test_transforms

    @property
    def collator_fn(self):
        return self._dataset.collator_fn(raw_texts=True)

In [177]:
datamodule = TweetsDataModule(batch_size=16)
datamodule.setup()

File exists: tweets_cleaned.csv


In [178]:
train_loader = datamodule.train_dataloader()
val_loader = datamodule.val_dataloader()
test_loader = datamodule.test_dataloader()

In [179]:
len(train_loader), len(val_loader), len(test_loader)

(22, 63, 63)

In [180]:
a, b, c, d = next(iter(train_loader))

Labels

In [181]:
a

tensor([1, 0, 0, 0, 0, 2, 0, 0, 1, 0, 1, 0, 0, 1, 0, 2])

Embeddings

In [182]:
b

(tensor([[ 0.1030,  0.4800, -0.5092,  ..., -0.0370, -1.3354,  0.9289],
         [-0.0952, -0.0464, -0.0794,  ...,  0.0071, -0.0759,  0.0163],
         [ 0.0466,  0.2132, -0.0074,  ...,  0.0091, -0.2099,  0.0539],
         ...,
         [-0.1937, -0.2979,  0.3024,  ...,  0.0618,  0.2053, -0.0833],
         [-0.0769, -0.0212,  0.2127,  ...,  0.1835, -0.2918, -0.0465],
         [ 0.2336, -0.3992, -0.2368,  ..., -0.4330,  0.0723,  0.4403]]),
 tensor([[ 2.3364e-01, -3.9918e-01, -2.3682e-01, -3.2494e-02, -4.1984e-01,
           4.0952e-01, -4.5269e-01,  2.5497e-01,  1.1024e-01, -1.7710e+00,
           5.0734e-01, -3.5370e-01, -5.4218e-01,  2.7641e-01, -2.3521e-01,
          -2.4534e-01, -2.7927e-01,  1.4222e-01, -1.3010e-01, -2.7662e-02,
           2.8358e-02,  3.8252e-01, -1.5431e-01,  1.2432e-02,  1.2361e-01,
           2.6327e-02,  1.8822e-01, -6.4913e-01,  1.6248e-01,  2.5412e-02,
          -2.0837e-01,  2.6968e-01, -5.3579e-01, -3.3051e-01, -8.7098e-01,
           2.5305e-01,  9.1478e-0

Lengths

In [183]:
c

tensor([17,  1, 24, 37,  8,  5, 24, 14, 25, 20, 18, 12, 11, 26, 27, 31])

Actual Tweets

In [184]:
d

('Obama Respects the Supreme Court Says Eric Holder, Violence in Syria Continues in Anticipation of... http://t.co/5QBOVrBw #libertario #tlot',
 '#tcot... http://t.co/oVMu9fKA',
 'President Obama ^ Lindsay Lohan RUMORS beginning ^ 1987 Analyst64 was protected ^ Future time-line indicator ^ Scramble scam mode video.',
 'RT @ohgirlphrase: American kid "You\'re from the UK? Ohhh cool, So do you have tea with the Queen?". British kid: "Do you like, go to Mcdonalds with Obama?',
 'Obama campaign wants to train army of women http://t.co/48O3o6jd',
 'Happy Passover, love Obama http://t.co/gHQ3NrWP',
 'RT @jmimac351: @EWErickson $4 gas, high unemployment & Obama is worried about Augusta National. This is smoke and mirrors for utter failure. #cantwait2vote',
 'RT @cannabis_times: Drug Policy Groups Unite to Demand End to Medical Marijuana Raids - http://t.co/y1W2HmGS via @Shareaholic',
 '#edshow  My President is standing up,speaking up,fighting back and I am so glad he has taken the gloves off.